Updated to node20 and dependencies
checkdigit/hash pull request #23
Opened 2024-03-13 17:37 UTC by jpolavar

Closes #22

2024-03-25 21:20 UTC, adcreare requested changes
Looks good - publish action needs to be updated to the latest action for a public repo.

2024-03-25 21:20 UTC, adcreare commented on .github/workflows/publish.yml
This needs to be updated to the "standard" publish action for a public repo

2024-03-25 22:32 UTC, adcreare approved these changes
LGTM

2024-03-26 20:11 UTC, adcreare approved these changes
LGTM

2024-03-26 20:13 UTC, merged

2024-03-26 20:17 UTC, jpolavar commented
@adcreare https://github.com/checkdigit/hash/actions/runs/8442321597/job/23123476131 seems audit signature failed